#   week:
#       class_session:
#           
#
1:
    -
        class_num: 1
        title: Introduction
        date: 28-08-2017
    -  
        class_num: 2
        title: Threat Modeling
        date: 30-08-2017
        due_before:
            -
                name: 'Quiz: Threat Modeling'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Threat Modeling"
2:
    -
        title: Labor Day
        date: 04-09-2017
        custom_css: success

    -
        class_num: 3
        title: "Cryptography &ndash; Introduction"
        date: 06-09-2017

        assigned_today:
            -
                name: "Install Cryptool 2.0 and submit screenshot"
3:
    -
        class_num: 4
        date: 11-09-2017

        title: "Cryptography &ndash; Hashes & Symmetric"
        due_before:
            -
                name: 'Quiz: Anderson, Ch. 5, pp. 129-149'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Symmetric"
    -
        class_num: 5
        date: 13-09-2017

        title: "Cryptography &ndash; Asymmetric"
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Asymmetric"
    -
        date: 15-09-2017
        due_tonight:
            -
                name: 'Email your PGP public key to Dr. Eargle (see Lab &ndash; Asymmetric)'
4:
    -
        class_num: 6
        date: 18-09-2017
        title: "Cryptography &ndash; Digital Certificates and PKI"
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Digital Certificates"
    -
        class_num: 7
        date: 20-09-2017

        title: "Codes Video"
5:
    -
        class_num: 8
        title: Physical Security
        date: 25-09-2017
        due_before:
            -
                name: 'Quiz: Anderson, Chapter 11'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Physical Security"
    -
        class_num: 9
        date: 27-09-2017

        title: Introduction to Computer Networking
6:
    -
        class_num: 10
        date: 02-10-2017
        title: Introduction to Linux
    -
        class_num: 11
        date: 04-10-2017
        title: Vulnerability Scanning
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Vulnerability Scanning"
7:
    -
        class_num: 12
        title: Vulnerability Exploitation
        date: 09-10-2017
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Exploitation"
    -
        class_num: 13
        title: System Hardening
        date: 11-10-2017

        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Hardening"
8:
    -
        class_num: 14
        title: Authentication and Passwords
        date: 16-10-2017
        due_before:
            -
                name: 'Quiz: Anderson Ch. 2, pp. 31-39, 56-58'

    -
        class_num: 15
        title: Password Cracking
        date: 18-10-2017
        due_before:
            -
                name: 'Quiz: Goodin, "Why passwords have never been weaker"'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Password Cracking"
9:
    -
        class_num: 16
        title: Midterm &ndash; no class
        custom_css: danger
        date: 23-10-2017
        assigned_today:
            -
                name: "Midterm Assigned"
            
    -
        class_num: 17
        title: Midterm &ndash; no class
        custom_css: danger
        date: 25-10-2017

10:
    -
        class_num: 18
        title: Web application security (SQL Injection; XSS)
        date: 30-10-2017
        due_before:
            -
                name: 'Quiz: Clarke, Chapter 1'
            -
                name: 'Quiz: Stuttard and Pinto, Attacking Users: Cross-site Scripting, pages 431–451'
        assigned_today:
            -
                name: "Lab &ndash; SQL Injection (extra credit)"
    -
        class_num: 19
        title: Human Element
        date: 01-11-2017
        due_before:
            -
                name: 'Quiz: Schneier, "The Security Mirage"; Anderson, Chapter 2, pp. 17-30, 40-42; Honan, "Cosmo"'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Social Engineering (extra credit)"
        due_tonight:
            -
                name: '<b>Midterm due</b>'
    -
        title: Film "Zero Days" screening
        date: 03-11-2017
11:
    -
        class_num: 20
        title: Network Security Monitoring
        date: 06-11-2017
        due_before:
            -
                name: 'Quiz: Bejtlich, Chapter 1'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Network Security Monitoring (extra credit)"
    -
        class_num: 21
        title: Network Security Monitoring (in-class lab)
        date: 08-11-2017

12:
    -
        class_num: 22
        title: Information Privacy
        date: 13-11-2017
        due_before:
            -
                name: 'Quiz: "The collapse of the US-EU Safe Harbor: Solving the new privacy Rubik''s Cube"'
        assigned_today:
            -
                name: "Assigned today: Lab &ndash; Privacy"
    -
        class_num: 23
        title: Information Security in Organizations
        date: 15-11-2017

13:
    -
        title: Fall Break
        date: 20-11-2017
        custom_css: success

    -
        title: Fall Break
        date: 22-11-2017
        custom_css: success

14:
    -
        class_num: 24
        title: Security and Society
        date: 27-11-2017

        
    -
        class_num: 25
        title: USENIX Enigma talks
        date: 29-11-2017

15:
    -
        class_num: 26
        title: Presentations
        date: 04-12-2017

    -
        class_num: 27
        title: Presentations
        date: 06-12-2017

    -
        title: Film "Citizenfour" screening
        date: 08-12-2017
        
16:
    -
        class_num: 28
        title: Course wrap-up
        date: 11-12-2017

    -
        class_num: 29
        title: No class
        date: 13-12-2017
        due_tonight:
            -
                name: '"Citizenfour" report'
            -
                name: '"Zero Days" report'
            -
                name: Security book report
            -
                name: Book extra credit report
            -
                name: Movie extra credit report
17:
    -
        title: Final exam
        date: TBA
        custom_css: danger

       