#   week:
#       class_session:
#           
#
1:
    -
        class_num: 1
        title: Introduction
        date: 28-08-2017
    -  
        class_num: 2
        title: Threat Modeling
        date: 30-08-2017
        readings:
            - "<a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBl_IAKxtg8x50_hgXsJ4xBTUVDI05oLFtZGwCOg_NgpNBIBjUQiopVgD2nRWALa9ibgYNN9cQZw_d0mR4pzHe2MwAdLpDPHT4BHSsiDnouluilQIAZj8pTQ'>Secrets & Lies</a> Chapters 19 and 21"
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Threat Modeling'
        assigned_today:
            -
                name: "Lab &ndash; Threat Modeling"
2:
    -
        title: Labor Day
        date: 04-09-2017
        custom_css: success

    -
        class_num: 3
        title: "Cryptography &ndash; Introduction"
        date: 06-09-2017

        assigned_today:
            -
                name: "Install Windows VM if necessary"
            -
                name: "Install Cryptool 2.0 and submit screenshot"
3:
    -
        class_num: 4
        date: 11-09-2017

        title: "Cryptography &ndash; Hashes & Symmetric"
        readings:
            - <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c05.pdf'>Anderson, Ch 5,</a> pp. 129-149
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBl_IAKxtg8x50_hgXsJ4xBTUVDI05oLFtZGwCOg_NgpNBIBjUQiopVgD2nRWALa9ibgYNN9cQZw_d0mR4pzHe2MwAdLpDPHT4BHSsiDnouluilQIAZj8pTQ'>Secrets & Lies</a> Chapters 6 & 7 (optional but highly recommended)
        due_before:
            - name: "Install Cryptool 2.0 and submit screenshot"
            - name: '<span class="label label-danger">Quiz:</span> Anderson, Ch. 5, pp. 129-149'
        assigned_today:
            - name: "Lab &ndash; Symmetric"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Threat Modeling'
    -
        class_num: 5
        date: 13-09-2017

        title: "Cryptography &ndash; Asymmetric"
        assigned_today:
            -
                name: "Lab &ndash; Asymmetric"
    -
        date: 15-09-2017
        due_tonight:
            -
                name: 'Email your PGP public key to Dr. Eargle (see Lab &ndash; Asymmetric)'
4:
    -
        class_num: 6
        date: 18-09-2017
        title: "Cryptography &ndash; Digital Certificates and PKI"
        assigned_today:
            -
                name: "Lab &ndash; Digital Certificates"
        readings:
            - "Online: Moxie Marlinspike: <a href='http://vimeo.com/32097738'>SSL And The Future Of Authenticity</a>"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Symmetric Encryption and Hashing'
            
    -
        class_num: 7
        date: 20-09-2017

        title: "Codes Video"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Asymmetric Encryption'
5:
    -
        class_num: 8
        title: Physical Security
        date: 25-09-2017
        readings:
            - <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c11.pdf'>Anderson, Chapter 11</a>
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Anderson, Chapter 11'
        assigned_today:
            -
                name: "Lab &ndash; Physical Security"
    -
        class_num: 9
        date: 27-09-2017

        title: Introduction to Computer Networking
        activities:
            - "Goal for today: setup your vms and ping them"
        readings:
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbU5lBl_IAKxtg8x50_hgXsJ4xBTUVDI05oLFtZGwCOg_NgpNBIBjUQiopVgD2nRWALa9ibgYNN9cQZw_d0mR4pzHe2MwAdLpDPHT4BHSsiDnouluilQIAZj8pTQ'>Secrets & Lies</a> Chapters 11 & 12
6:
    -
        class_num: 10
        date: 02-10-2017
        title: Introduction to Linux (in-class lab)
        activities:
            - Using your Kali VM, go through <a href='http://www.tldp.org/LDP/intro-linux/intro-linux.pdf'>this Linux tutorial,</a> chapters 1–7,10.
            - Also learn about <ul>
                    <li><a href='https://www.linux.com/learn/linux-101-introduction-sudo'>sudo</a></li>
                    <li>man id</li>
                    <li>man 5 passwd</li>
                    <li>man 5 group</li>
                    <li>ssh & scp</li>
                </ul>
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Physical Security'
    -
        class_num: 11
        date: 04-10-2017
        title: Vulnerability Scanning
        assigned_today:
            -
                name: "Lab &ndash; Vulnerability Scanning"
        
7:
    -
        class_num: 12
        title: Vulnerability Exploitation
        date: 09-10-2017
        assigned_today:
            -
                name: "Lab &ndash; Exploitation"
    -
        class_num: 13
        title: System Hardening
        date: 11-10-2017

        assigned_today:
            -
                name: "Lab &ndash; Hardening"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Vulnerability Scanning'
8:
    -
        class_num: 14
        title: Authentication and Passwords
        date: 16-10-2017
        readings:
            - <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c02.pdf'>Anderson, Chapter 2,</a> pp. 31-39, 56-58
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Anderson Ch. 2, pp. 31-39, 56-58'

    -
        class_num: 15
        title: Password Cracking
        date: 18-10-2017
        readings:
            - Goodin, <a href='https://arstechnica.com/security/2012/08/passwords-under-assault/'>"Why passwords have never been weaker"</a>
            - 'Gosney, <a href="http://arstechnica.com/security/2016/06/how-linkedins-password-sloppiness-hurts-us-all/">How LinkedIn’s password sloppiness hurts us all</a>'
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Goodin, "Why passwords have never been weaker"'
        assigned_today:
            -
                name: "Lab &ndash; Password Cracking"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Exploitation'
            - name: '<span class="label label-success">Lab:</span> Hardening'
9:
    -
        class_num: 16
        title: Midterm Prep
        custom_css: ''
        date: 23-10-2017
        assigned_today:
            -
                name: "<span class='label label-danger'>Midterm</span>"
            
    -
        class_num: 17
        title: Midterm &ndash; no class
        custom_css: ''
        date: 25-10-2017
        activities:
            - "no class today; work on midterm"
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Password Cracking'

10:
    -
        class_num: 18
        title: Web application security &ndash; SQL Injection
        date: 30-10-2017
        readings:
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbQRuBDUFtVUtLYBJihhytBOGbgXtEgY7mZnqWeo7gW1EtQKdGAduuxhyw0RED0JkthhacDIrBgT4KmXlZ4HVJeQqJoAvvs4sVgL1shZTUNGBPD1iIqri5hjh76JYmw3uY8dCxj_gkC2AFa2FsCLq9QBOiLLE4G1h8AIuWkuL4shzwlGRxPMJ55sagE0GVIWphpXM8WBl0uWS8JTDdWlggVAHrmKLE3JTMdPA1HwWQUyLigf0IE_DpokoQVZB5YLh0SUVJPOiOXQtTE5Dj5LAqQlIANwWxNwphFZqDIBOuCGk0zxEVXgAYH4Xm'>Clarke, SQL Injection</a>, Chapter 1
            - <a href='www.whitehatsec.com/blog/saving-systems-from-sqli/'>Jeremiah Grossman, Saving Systems from SQLi</a>
            
        due_before:
            - name: '<span class="label label-danger">Quiz:</span> Clarke, Chapter 1'
            
        activities:
            - "Lab &ndash; SQL Injection (in-class only)"
        
    -
        class_num: 19
        title: Web application security &ndash; XSS
        date: 01-11-2017
        readings:
            - "<a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbQRuBDUF7Gs1NjUzMmSFHK4FPG4McV84FqncsjU2A9SMHbEQE1BQ2N7fgZFAFhpACsBBRQJrDVchIBC0zUC9WAA0ogxqg3Awabq4hzh66pcnwnmW8sZkB6AiIeBQTjbkZVCBKYaVtPHgmErr8Md7EwBiYcEH7dpQhyoCVRlFibkpmOvjejgLIsQ_xQEUWRqBrEOQgqiATu3BpoPfMgc0lkG1KWBWUVJQQqQh0ZouZsRFuqxAK4KYgtkzBlYEqewMLhLewKkJ4nujgBADKlY-Z'>Stuttard and Pinto, The Web Application Hacker's Handbook</a>, Chapter 12, sections 'Varieties of XSS' and 'XSS Attacks in Action'"
        due_before:
            - name: '<span class="label label-danger">Quiz:</span> Stuttard and Pinto, Attacking Users: Cross-site Scripting, pages 431–451'
        activities:
            - "Lab &ndash; XSS (In-class only)"
        due_tonight:
            - name: '<span class="label label-danger">Midterm due</span>'
    
    -
        title: Film "Zero Days" screening
        date: 03-11-2017
        
    
11:

    
        
                
    -
        class_num: 21
        title: Network Security Monitoring
        date: 06-11-2017
        readings:
            - <a href='http://ucblibraries.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42JgAfZbUxkhpymZApsHwAYxaGc5Et8A1ATmMgJNmgHTg5kZB2xQBFjfg4604mQArTdQgO0TUshPU8iDLIpWKIbe6qaQC07yoLEvbgYNN9cQZw_d0mR4FzPe2MwAdBZEPIq5xtwMahClxdmZOTnFwIIuHtSWLTYyqTCPT8ouBt-yZ2wCOkNQBaIQVj7Hg-cuoQsm4w1NzY0swEeHykGUQSZ54wsgJ0TEG4IqXmBTCahACauCkooSZEXKMEWIjU8Is-B2Ee1NAGX0cjY'>Bejtlich, The Practice of Network Security Monitoring,</a> Chapter 1
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Bejtlich, Chapter 1'
        assigned_today:
            -
                name: "Lab &ndash; Network Security Monitoring (extra credit)"
    
    -
        class_num: 22
        title: Network Security Monitoring (in-class lab)
        date: 08-11-2017
    
    
12:
    -
        class_num: 20
        title: Human Element
        date: 13-11-2017 
        readings:
            - <a href='https://www.ted.com/talks/bruce_schneier'>Schneier, "The Security Mirage"</a>
            -  <a href='http://www.cl.cam.ac.uk/~rja14/Papers/SEv2-c02.pdf'>Anderson, Chapter 2,</a> pp. 17-30, 40-42
            - <a href='http://www.wired.com/2012/09/cosmo-the-god-who-fell-to-earth/all/'>"Cosmo, the Hacker ‘God’ Who Fell to Earth," by Mat Honan</a>
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> Schneier, "The Security Mirage"; Anderson, Chapter 2, pp. 17-30, 40-42; Honan, "Cosmo"'
        activities:
            - "Lab &ndash; Social Engineering (In-class only)"
    
    -
        class_num: 23
        title: Information Privacy
        date: 15-11-2017
        readings:
            - 'Brad Smith, <a href="https://blogs.microsoft.com/on-the-issues/2015/10/20/the-collapse-of-the-us-eu-safe-harbor-solving-the-new-privacy-rubiks-cube/">"The collapse of the US-EU Safe Harbor: Solving the new privacy Rubik''s Cube"</a>'
        due_before:
            -
                name: '<span class="label label-danger">Quiz:</span> "The collapse of the US-EU Safe Harbor: Solving the new privacy Rubik''s Cube"'
        assigned_today:
            -
                name: "Lab &ndash; Privacy"
    

13:
    -
        title: Fall Break
        date: 20-11-2017
        custom_css: success

    -
        title: Fall Break
        date: 22-11-2017
        custom_css: success

14:

    -
        class_num: 24
        title: Information Security in Organizations
        date: 27-11-2017
        
    -
        class_num: 25
        title: Security and Society
        date: 29-11-2017
        due_tonight:
            - name: '<span class="label label-success">Lab:</span> Privacy and Anonymity'
        

15:
    -
        class_num: 27
        title: Presentations
        date: 04-12-2017

    -
        class_num: 28
        title: Presentations
        date: 06-12-2017

    -
        title: Film "Citizenfour" screening
        date: 08-12-2017
        
16:

    -
        class_num: 26
        title: USENIX Enigma talks
        date: 11-12-2017
    
    -
        class_num: 29
        title: Course wrap-up
        date: 13-12-2017
        
        due_tonight:
            -
                name: '"Citizenfour" report'
            -
                name: '"Zero Days" report'
            -
                name: Book extra credit report
            -
                name: Movie extra credit report
        
17:
    -
        title: Final exam
        date: TBA
        custom_css: danger

       